### PR TITLE
KMP Algorithm

### PR DESCRIPTION
**Pull request by flow6979**

### CODE REVIEW

**Comment by Abhijit25Mishra** [comment]
Hey can u add some explanation for this in the explanation folder. also add a simple example as well.

**Comment by flow6979** [comment]
> Hey can u add some explanation for this in the explanation folder. also add a simple example as well.

ok i will add.

**Comment by flow6979** [comment]
> Hey can u add some explanation for this in the explanation folder. also add a simple example as well.

now you can merge brother. I have created the explanation file.

**Comment by flow6979** [comment]
@Abhijit25Mishra please review it

**Comment by Abhijit25Mishra** [comment]
Nice work. 👍

**Pull request merged**
