### PR TITLE
adding sieve

### PR DESCRIPTION
**Pull request by Pulkitt23**
This sieve is better than O(N*log(log(N)) as it works in O(N)

### CODE REVIEW

**Review by Abhijit25Mishra — CHANGES_REQUESTED** [review]
Hey this file seems to be empty, please check again and confirm.

**Comment by Pulkitt23** [comment]
Yes It was my first contribution so my apologies

**Comment by Pulkitt23** [comment]
Please let me know if I need to improve this code or else if you have another task please assign it to me

**Comment by Abhijit25Mishra** [comment]
Change the prefix in the json file 
remove the comments in the snippet 
add an explanation with example.

**Comment by Pulkitt23** [comment]
I have added explanation too. As example would be too obvious because it is to print prime numbers till N. Also added source of this explanation in the reference.

**Comment by Abhijit25Mishra** [comment]
Alright good. 

By the way you don't have to close the merge, that's usually done when the work on the issue is stopped for some reason. 
i understand that your new here. so i keep reopening it and making further comments.

Its best to make pull request, write any comment if necessary and then just leave as it is, maintainers will review the comment and the commits and give feedback.

**Pull request merged**
